name: Deploy

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: [self-hosted, qode]
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci --legacy-peer-deps
      - run: source ~/.env
      - run: touch .env.production
      - run: echo "NEXTAUTH_SECRET='${{ secrets.NEXTAUTH_SECRET }}'" >> .env.production
      - run: echo "NEXTAUTH_URL='${{ secrets.NEXTAUTH_URL }}'" >> .env.production
      - run: echo "GITHUB_ID=${{ secrets.ID_GITHUB }}" >> .env.production
      - run: echo "GITHUB_SECRET=${{ secrets.SECRET_GITHUB }}" >> .env.production
      - run: echo "MONGODB_URL=${{ secrets.MONGODB_URL }}" >> .env.production
      - run: echo "NEXT_PUBLIC_TINY_EDITOR_API_KEY=${{ secrets.NEXT_PUBLIC_TINY_EDITOR_API_KEY }}" >> .env.production
      - run: npm run build --if-present
      - run: pm2 restart qode --update-env
